Upload avatar
iqbalbaharum/fekreno pull request #45
Opened 2021-02-06 07:33 UTC by HaziqRauf

Add function to upload user avatar. Close #5

2021-02-08 05:55 UTC, iqbalbaharum requested changes

2021-02-08 05:55 UTC, iqbalbaharum commented on src/pages/Index.vue
> +     this.dialogPhoto = false
The avatar is assign to local variables, but its not submitted to backend to be store.

2021-02-10 09:39 UTC, HaziqRauf commented
The url for the avatar has been stored at the database. Review required.

2021-03-22 13:33 UTC, iqbalbaharum approved these changes

2021-03-22 13:33 UTC, merged